version: '2.2'
services:

  kafka-cluster:
    container_name: kafka-cluster
    image: landoop/fast-data-dev:2.3.0
    environment:
      ADV_HOST: 127.0.0.1         
      RUNTESTS: 0                 
      CONNECTORS: debezium-postgres,cassandra,s3,mongodb
      #AWS_ACCESS_KEY_ID: "ACCESS KEY GOES HERE "
      #AWS_SECRET_ACCESS_KEY: "SECRET KEY  GOES HERE "
      SAMPLEDATA: 0
    ports:
      - 2181:2181                   # Zookeeper
      - 3030:3030                   # Landoop UI
      - 8081-8083:8081-8083         # REST Proxy, Schema Registry, Kafka Connect ports
      - 9581-9585:9581-9585         # JMX Ports
      - 9092:9092                   # Kafka Broker
    volumes:
      - ./target/plugin/:/connectors/


  postgres:

    image: debezium/postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=spotify_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data:rw

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8080:80"

